### ISSUE TITLE
Define user profiles & the load pattern for each profile to be used based on the solution diagram

### ISSUE THREAD

**Issue by NadHodeGW** [filetrust/k8-performance-use-cases#1]

**Comment by RhiaRodriguez** [comment]
I can work on this one.

**Comment by NadHodeGW** [comment]
Removing this issue from Upwork log

**Comment by RhiaRodriguez** [comment]
[GlasswallPOC.jmx.zip](https://github.com/filetrust/k8-performance-use-cases/files/5151515/GlasswallPOC.jmx.zip)
