### ISSUE TITLE
Set up a docker image using the provided Jmeter docker file to execute Jmeter tests locally through the squid proxy

### ISSUE THREAD

**Issue by NadHodeGW** [filetrust/k8-performance-use-cases#2]
We have a working example for Jmeter & Docker

https://github.com/filetrust/file-rebuild-performance-tests/blob/master/docker/FileRebuildPerformanceTest/Dockerfile

Docker file needs to be edited to update the test being run, and needs to be configured to send traffic through squid proxy

**Comment by MaNe2020** [comment]
I can start working on this one. Marija

**Comment by hongson1981** [comment]
Link https://github.com/filetrust/file-rebuild-performance-tests/blob/master/docker/FileRebuildPerformanceTest/Dockerfile is unreachable, please check again
I found that link below available, can we use it  ?
https://github.com/filetrust/cloudsdk-rebuild-api-performance-tests

**Comment by MaNe2020** [comment]
@hongson1981 this is a great link, but I cannot see dockerfile anywhere. Tried few more resources through this git but no luck.
@NadHodeGW can you check where we can find this dockerfile? Thanks

**Comment by NadHodeGW** [comment]
> Link https://github.com/filetrust/file-rebuild-performance-tests/blob/master/docker/FileRebuildPerformanceTest/Dockerfile is unreachable, please check again
> I found that link below available, can we use it ?
> https://github.com/filetrust/cloudsdk-rebuild-api-performance-tests

@hongson1981 , No this repo should now be accessible; try assigning yourself again.
See the docker file in the the master branch: https://github.com/filetrust/k8-performance-use-cases/blob/master/Dockerfile

**Comment by hongson1981** [comment]
![image](https://user-images.githubusercontent.com/29745336/91285349-520f7e80-e7b7-11ea-8247-0bf1e6778f03.png)
I have just tried. Still 404 not found

**Comment by NadHodeGW** [comment]
@hongson1981, That is not the link in my previous comment, please access it here:  https://github.com/filetrust/k8-performance-use-cases/blob/master/Dockerfile or look in the master branch of this repo

**Comment by MaNe2020** [comment]
@NadHodeGW this dockerfile is using JMeter 3.3 but the best practice is to use the newest one. If there is no specific requirement for 3.3 is it ok to change JMeter version to 5.3?

**Comment by NadHodeGW** [comment]
@MaNe2020 , yes should be fine
