### ISSUE TITLE
Configure a pod to run artillery tests through the Squid proxy & ICAP

### ISSUE THREAD

**Issue by NadHodeGW** [filetrust/k8-performance-use-cases#3]

**Comment by hongson1981** [comment]
I can work on this one.

**Comment by NadHodeGW** [comment]
Cool, @hongson1981, make use of the work done in the repo below for this task 
https://github.com/filetrust/k8-traffic-generator

**Comment by hongson1981** [comment]
Deploy artillery  to docker : Success and work


Deploy Squid proxy with ICAP to docker : Success and work
Next step : Config and run artillery via squid proxy

**Comment by hongson1981** [comment]
[squid_icap_dockerfile.zip](https://github.com/filetrust/k8-performance-use-cases/files/5155881/squid_icap_dockerfile.zip)
